### ISSUE TITLE
Async/Await support

### ISSUE THREAD

**Issue by davidgraeff** [davidgraeff/firestore-db-and-auth-rs#10]
As soon as Rust 1.39 hits stable and the used reqwest crate is released with async support, this library should be updated to offer blocking and async APIs.

**Comment by davidgraeff** [comment]
Initial preparations done with 0.6. I'm not sure yet if the async API should have "_async" suffixes or an own namespace via an "nonblocking" module.

**Comment by felipellrocha** [comment]
How's progress for this work coming? I ran into a use case

**Comment by davidgraeff** [comment]
It's not that complicated to implement, all underlying libraries have good asnyc support by now. 

I didn't have enough pressure to lay out the design yet.  Let me have a look this week.

**Comment by davidgraeff** [comment]
Depends on issue https://github.com/seanmonstar/reqwest/issues/1060 (reqwest for tokio 1.0).
Related MR is https://github.com/seanmonstar/reqwest/pull/1076

With tokio 1.0 there is finally a mostly stable upstream foundation for async support.

**Comment by davidgraeff** [comment]
Done
