### ISSUE TITLE
Empty `mapValue` in response causes JSON parser error

### ISSUE THREAD

**Issue by JadedEvan** [davidgraeff/firestore-db-and-auth-rs#16]
**Describe the bug**
When attempting to parse a Firestore document whose `mapValue` returns an empty JSON object parsing fails and causes a reqwest `Decode` error because the required `fields` key cannot be found. Note that it is possible to have Firestore doc with a map value that is an empty object.

This appears to originate in the type definition of `MapValue` because it will not currently accept an `Option` type and must have `fields` present in the JSON response. Current definition:

```
pub struct MapValue {
    pub fields: HashMap<String, Value>,
}
```

When it should be

```
pub struct MapValue {
    pub fields: Option<HashMap<String, Value>>,
}
```

**To Reproduce**

Create a Firestore document that contains an object whose values are empty like this:

```json
{
  "name": "projects/firestore-db-and-auth/databases/(default)/documents/user/1",
  "fields": {
    "gender": {
      "stringValue": "male"
    },
   "age": {
      "integerValue": "35"
    },
    "profile": {
       "mapValue": {}
    }
  },
  "createTime": "2020-04-28T14:52:51.250511Z",
  "updateTime": "2020-04-28T14:52:51.250511Z"
}
```

See that when this document is parsed via the crate, it raises an error of `errors::Request` masked underneath a `reqwest` error:

```
reqwest::Error {
  kind: Decode,
  source: Error("missing field `fields`", line: 77, column: 26),
}
```

Note that the line number will vary as the ordering of the fields in the document changes in each HTTP response.

**Expected behavior**

This does not cause an error and allows for an empty `mapValue` object from the Firestore document

**Comment by JadedEvan** [comment]
FYI I'm currently working on some tests to demonstrate this bug to include within the crate. I'll see if I can weave the `Option` type as suggested in the original report to make this work as expected

**Comment by davidgraeff** [comment]
Thanks for the report. A unit test for this kind of documents will help a lot.

I was pretty sure "fields" was mandatory at some point, but I might as well have misread the documentation.

**Comment by davidgraeff** [comment]
Should be fixed now
