### ISSUE TITLE
documents::delete does not report failures

### ISSUE THREAD

**Issue by dbdr** [davidgraeff/firestore-db-and-auth-rs#2]
When a document::write fails (e.g. because of missing permissions), the function correctly returns an Err Result. In contract, it seems to me that document::delete always returns Ok even when the delete failed.

**Comment by davidgraeff** [comment]
You are right, I'll add a fix and a test

**Comment by davidgraeff** [comment]
Done. `cargo publish` is in progress. This and a few other bits changed the API, will be v0.2.

**Comment by dbdr** [comment]
Thanks!

The new version of delete has a println!, I suppose that's a leftover from debugging...

**Comment by davidgraeff** [comment]
Yes. Sorry for that. I just have setup some continuous integration services and I will add a rule to check for left over prints.

**Comment by dbdr** [comment]
I confirm that delete now correctly reports failure on missing permissions. Closing the issue.

Thanks a lot!
