### ISSUE TITLE
already mutably borrowed: BorrowError

### ISSUE THREAD

**Issue by yoannfleurydev** [davidgraeff/firestore-db-and-auth-rs#30]
**Describe the bug**

My [program](https://github.com/BearStudio/twitch-listener/blob/main/src/main.rs) did stop with the following error: 

```
thread 'tokio-runtime-worker' panicked at 'already mutably borrowed: BorrowError', /Users/yfleury/.cargo/registry/src/github.com-1ecc6299db9ec823/firestore-db-and-auth-0.6.1/src/sessions.rs:308:45
```

Looking at the `sessions.rs` line (308 in the log, [488](https://github.com/davidgraeff/firestore-db-and-auth-rs/blob/master/src/sessions.rs#L488) in this repo source code) it seems that the call to `.borrow()` is panicking.

![image](https://user-images.githubusercontent.com/3920615/140648435-a9fb65fd-ba27-443b-83d5-e2896ba7999f.png)

I'm kind of new to Rust so I'm not sure everything is right on my side.

**To Reproduce**

Here is my program https://github.com/BearStudio/twitch-listener

1. Run with `cargo run`
2. Use documents like 

```rust
struct Question {
    id: String,
    username: String,
    message: String,
    timestamp: String,
}
```

**Expected behavior**

I expect my program not to panic.

**Comment by limpit666** [comment]
Hi @yoannfleurydev,
I am getting this same issue as well, did you ever find a solution?

**Comment by yoannfleurydev** [comment]
> Hi @yoannfleurydev,
> I am getting this same issue as well, did you ever find a solution?

Hi, no, not at this time sorry.

**Comment by limpit666** [comment]
So I fixed the issue by reducing the scope of the borrows but for some reason it is still failing to renew the authorization, there doesn't seem to be any other errors in the process. 

```rust
        fn access_token(&self) -> String {
            //let mut jwt = ;

            if jwt_update_expiry_if(&mut self.jwt.borrow_mut(), self.refresh_minutes) {
                if let Some(secret) = self.credentials.keys.secret.as_ref() {
                    match self.jwt.borrow().encode(&secret.deref()) {
                        Ok(v) => {
                            match v.encoded() {
                                Ok(v2) => {
                                    self.access_token_.swap(&RefCell::new(v2.encode()));
                                }
                                Err(e) => {
                                    panic!("{:?}", e)
                                }
                            }
                        }
                        Err(e) => {
                            panic!("{}", e);
                        }
                    }
                }
            }

            self.access_token_.borrow().clone()
        }
```

After the hour has passed requests start returning `APIError(401, "Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential.`
