### ISSUE TITLE
Get metadata of listed documents

### ISSUE THREAD

**Issue by dbdr** [davidgraeff/firestore-db-and-auth-rs#5]
If I understand correctly, documents::list will return an iterator of structs that mirror the content of the documents. Is there any way to get the metadata (e.g. names) of the documents in a collection?

**Comment by davidgraeff** [comment]
Not yet. The paging REST API will return the documents anyway afaik.

The `query` call could be modified however to only contain document metadata.
Right now it actively fetches all referenced documents of a successful query.

**Comment by dbdr** [comment]
It looks to me as if `list` also has the right information as dto::Document which contains the metadata, it's just not part of the public API.

What about a `list_documents` that would return an iterator of some Document object, and another function to get the contents of a Document?

**Comment by davidgraeff** [comment]
The iterator could return a tuple (metadata, content) on each iteration.

The data has already been fetched so I don't see a point in throwing it away (by only making the meta data available). WDYT?

**Comment by dbdr** [comment]
Ah, I didn't realize all the data was available at once. Then you're right, it definitely makes sense to make all of it available.

Ergonomically, it might be nicer to have a Document struct that contains both the metadata and a data/contents field, but then it needs to be parameterized by the content type. If that complicates things too much, a tuple is also fine.

**Comment by dbdr** [comment]
Metadata is available now, thanks!
