### ISSUE TITLE
Integers that don't fit into u32 get silently mapped to null

### ISSUE THREAD

**Issue by dbdr** [davidgraeff/firestore-db-and-auth-rs#8]
I think the issue is here: https://github.com/davidgraeff/firestore-db-and-auth-rs/blob/e8fd5262d9256d88a0b4af16cb5bf864ef4e8d97/src/firebase_rest_to_rust.rs#L31

**Comment by davidgraeff** [comment]
The u32 type is indeed wrong. The documentation[1] defines i64 as integer type.

[1] https://firebase.google.com/docs/firestore/reference/rest/v1/Value
